### ISSUE TITLE
SAM_RS：Urban测试爆内存

### ISSUE THREAD

**Issue by Gcx0707** [sstary/SSRS#43]
Thank you for your outstanding work. When I run the code with the Urban dataset, the memory usage shoots up to 100% during validation, causing it to stop. However, when using the Vaihingen dataset, it's only 12%. What could be the reason for this? Looking forward to your reply.

**Comment by sstary** [comment]
Hello, this is because Urban's test set is much larger than ISPRS Vaihingen, and during the training phase, when the test function is called, the predicted values of all the test images are recorded in an array, which may burst the memory. One approach is that you reduce the test set index during the training phase, which does not significantly affect the selection of the best model, and then use the entire test set for the final test.

**Comment by Gcx0707** [comment]
> 您好，这是因为 Urban 的测试集比 ISPRS Vaihingen 大很多，并且在训练阶段，当调用测试函数时，所有测试图像的预测值都记录在一个数组中，这可能会使内存爆裂。一种方法是在训练阶段减少测试集索引，这不会显著影响最佳模型的选择，然后将整个测试集用于最终测试。

I understand now, thank you very much for your reply and guidance.
