### ISSUE TITLE
FTransUNet：the shape about input image

### ISSUE THREAD

**Issue by zhangjh100** [sstary/SSRS#68]
Hello, I got a question while using my own dataset. The shape of input image is 512*512, and the model I used is FTUNetFormer, and I have wirtten a utils.py for my dataset, but the process exits error, says that the input image shape ( 512, 512 ) does not match ( 256, 256 ), which part of the project should I make some change? Looking forward to your reply.

**Comment by sstary** [comment]
Hello, you need to modify two places:

Line 15 in SSRS/FTransUNet/utils.py:
WINDOW_SIZE = (512, 512) # Patch size

Line 33-34 in SSRS/FTransUNet/train.py:
config_vit.patches.grid = (int(512 / 16), int(512 / 16))
net = ViT_seg(config_vit, img_size=512, num_classes=6).cuda()

However, since the transformer part of the FTransUNet is pre-trained on images of size 256*256, although it can be loaded, its performance is not guaranteed. I hope it works well.

**Comment by zhangjh100** [comment]
But the model I used is FTUNetFormer, not FTransUNet

**Comment by sstary** [comment]
OK, then you need to modify Line 532 in SAM_RS/model/swintransformerv2.py
def __init__(self, img_size=512, patch_size=4, in_chans=3, num_classes=6,

This will enable the model's encoder to receive inputs of size 512. However, since the pre-trained Swintransformer only supports inputs of size 256, you can load the pre-trained model, but delete the specific layers in the model with the error messages in this part:
    if pretrained and weight_path is not None:
        # old_dict = torch.load(weight_path)['state_dict']
        old_dict = torch.load(weight_path)['model']
        model_dict = model.state_dict()
        del_keys = ['layers.0.blocks.1.attn_mask', 'layers.1.blocks.1.attn_mask', 'layers.3.blocks.0.attn.relative_coords_table', 'layers.3.blocks.0.attn.relative_position_index', 'layers.3.blocks.1.attn.relative_coords_table', 'layers.3.blocks.1.attn.relative_position_index']
        for k in del_keys:
            del old_dict[k]
        old_dict = {'backbone.'+ k: v for k, v in old_dict.items() if ('backbone.' + k in model_dict)}
        model_dict.update(old_dict)
        model.load_state_dict(model_dict)
        print('Load weight ', weight_path)

or you can only choose not to load the pre-trained model with the following modifications:
Line 982 in SSRS/SAM_RS/model/FTUNetFormer.py:
def ft_unetformer(pretrained=False, num_classes=6, freeze_stages=-1, decoder_channels=256,

However, this approach would significantly degrade model performance.

**Comment by zhangjh100** [comment]
您好！我换成了Vaiginhen数据集，使用FTUNetFormer训练，但是会报错AssertionError: Input image size (2557*1887) doesn't match model (256*256).  请问您在使用FTUNetFormer训练的时候，所有参数设置和使用UNetFormer是一样的吗

**Comment by sstary** [comment]
你这看上去是把整个大图输入了，这里的数据在输入之前是需要通过滑动窗口截取256*256的输入的，你要把sliding window和window size相关的检查下。
如果输入保持一致，FTUNetFormer和UNetFormer没有区别。

**Comment by zhangjh100** [comment]
请问您的代码在测试的时候，是将测试集的图片一次性都输入到CPU进行测试吗？如果测试集太大，CPU没办法一次性处理这么多图像的话，测试代码应该怎样修改呢？

**Comment by sstary** [comment]
你好，是训练过程中把每500batch一次的测试时的测试数减少，这样还是们筛选出最佳模型。然后最终选出来的模型使用完整测试集得到最终结果。

**Comment by zhangjh100** [comment]
但是最终测试的时候，如果测试集有几万张图像，是一次性全部送到网络测试吗？可不可以修改为一次读取10张图像，多读取几次进行测试？

**Comment by sstary** [comment]
如果你说的几万都是几千乘几千像素的，那不一定可以，因为都会存在那个pred中，就算分别读取，它也会很大。主要你这几万有点夸张，硬件需求太大了。

**Comment by zhangjh100** [comment]
几万的意思是测试集有几万张图像，每张图像大小为256*256

**Comment by sstary** [comment]
256大小的应该没问题，直接测试，24g显卡应该能跑

**Comment by sstary** [comment]
等等，你的一次性是啥意思？不是batch size等于几万吧？

**Comment by zhangjh100** [comment]
不好意思，今天才看到消息，就是，batch size是10，但是代码当中不是有一个return batch_size * 1000吗，这些我都没有修改，我的测试集是18000张 256 * 256 的图像，我看 train.py 当中的 test 函数的意思就是一次性将所有测试图片都输入到 CPU 当中进行测试的，并不是按照 batch size的大小将图像一次测试 batch size 张图像，然后多次测试

**Comment by zhangjh100** [comment]
不好意思，今天才看到消息，就是，batch size是10，但是代码当中不是有一个return batch_size * 1000吗，这些我都没有修改，我的测试集是18000张 256 * 256 的图像，我看 train.py 当中的 test 函数的意思就是一次性将所有测试图片都输入到 CPU 当中进行测试的，并不是按照 batch size的大小将图像一次测试 batch size 张图像，然后多次测试
